### ISSUE TITLE
cannot install packages

### ISSUE THREAD

**Issue by amidia** [adrianharabula/php-oci8#2]
hi 
i tried to install some oci8 wrapper with composer but keep getting error
how to add some cli on php-apache image
i keep stuck in here. any insight would be appreciated.

here is the error i got:
`composer require yajra/laravel-oci8
Using version ^5.5 for yajra/laravel-oci8
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yajra/laravel-oci8 v5.5.6 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - yajra/laravel-oci8 v5.5.5 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - yajra/laravel-oci8 v5.5.4 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - yajra/laravel-oci8 v5.5.3 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - yajra/laravel-oci8 v5.5.2 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - yajra/laravel-oci8 v5.5.1 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - yajra/laravel-oci8 v5.5.0 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - Installation request for yajra/laravel-oci8 ^5.5 -> satisfiable by yajra/laravel-oci8[v5.5.0, v5.5.1, v5.5.2, v5.5.3, v5.5.4, v5.5.5, v5.5.6].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/15-xml.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-dom.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-mbstring.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_pgsql.ini
    - /etc/php/7.0/cli/conf.d/20-pgsql.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-simplexml.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.0/cli/conf.d/20-wddx.ini
    - /etc/php/7.0/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.0/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.0/cli/conf.d/20-xsl.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.`

**Comment by adrianharabula** [comment]
Hello, it seems that oci8 extension is not running. Is this issue still available?

**Comment by adrianharabula** [comment]
i'm closing the issue; please reopen if it is still relevant for you.

**Comment by adrianharabula** [comment]
Hello, I think it's fixed in 3c03187a6ea281422f927bc563d6d6c15b949c37. Check it out! https://github.com/adrianharabula/php7-with-oci8/blob/master/php71/7.1.30-apache-stretch/oci-2.2.0/Dockerfile

**Comment by amidia** [comment]
> Hello, I think it's fixed in [3c03187](https://github.com/adrianharabula/php7-with-oci8/commit/3c03187a6ea281422f927bc563d6d6c15b949c37). Check it out! https://github.com/adrianharabula/php7-with-oci8/blob/master/php71/7.1.30-apache-stretch/oci-2.2.0/Dockerfile

thanks 
that's helped. 
i've came around with similar project right now.
